In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("Virat_Kohli.csv")

In [ ]:
df.head()

,No.,Runs,Against,Position,Innings,Venue,Ground,Date,Result
0,1,107,Sri Lanka,4,2,"Eden Gardens, Kolkata",Home,24-Dec-09,Won
1,2,102*,Bangladesh,3,2,"Sher-e-Bangla Cricket Stadium, Dhaka",Away,11-Jan-10,Won
2,3,118,Australia,3,2,"APCA-VDCA Stadium, Visakhapatnam",Home,20-Oct-10,Won
3,4,105,New Zealand,3,1,"Nehru Stadium, Guwahati",Home,28-Nov-10,Won
4,5,100*,Bangladesh,4,1,"Sher-e-Bangla Cricket Stadium, Dhaka",Away,19-Feb-11,Won

In [ ]:
df.tail()

,No.,Runs,Against,Position,Innings,Venue,Ground,Date,Result
75,76,121,West Indies,4,1,"Queen's Park Oval, Port of Spain",Away,20-Jul-23,Drawn
76,77,122*,Pakistan,3,1,"R. Premadasa Stadium, Colombo",Neutral,11-Sep-23,Won
77,78,103*,Bangladesh,3,2,"Maharashtra Cricket Association Stadium, Pune",Home,19-Oct-23,Won
78,79,101*,South Africa,3,1,"Eden Gardens, Kolkata",NaN,05-Nov,Won
79,80,117,New Zealand,3,1,"Wankhede Stadium, Mumbai",Home,15-Nov-23,Won

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   No.       80 non-null     int64
 1   Runs      80 non-null     object
 2   Against   80 non-null     object
 3   Position  80 non-null     int64
 4   Innings   80 non-null     int64
 5   Venue     80 non-null     object
 6   Ground    79 non-null     object
 7   Date      80 non-null     object
 8   Result    80 non-null     object
dtypes: int64(3), object(6)
memory usage: 5.8+ KB

In [ ]:
df.shape

(80, 9)

In [ ]:
df.columns

Index(['No.', 'Runs', 'Against', 'Position', 'Innings', 'Venue', 'Ground',
       'Date', 'Result'],
      dtype='object')

In [ ]:
df.describe()

           No.   Position   Innings
count  80.0000  80.000000  80.00000
mean   40.5000   3.500000   1.67500
std    23.2379   0.656033   0.67082
min     1.0000   2.000000   1.00000
25%    20.7500   3.000000   1.00000
50%    40.5000   3.000000   2.00000
75%    60.2500   4.000000   2.00000
max    80.0000   6.000000   4.00000

In [ ]:
df.isnull().sum()

No.         0
Runs        0
Against     0
Position    0
Innings     0
Venue       0
Ground      1
Date        0
Result      0
dtype: int64

In [ ]:
df.dtypes

No.          int64
Runs        object
Against     object
Position     int64
Innings      int64
Venue       object
Ground      object
Date        object
Result      object
dtype: object